services:
  nginx:
    image: nginx-shawdy
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    environment:
      NGINX_HOST: localhost
      PHP_UPSTREAM: php:9000
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      php:
        condition: service_healthy

  php:
    image: shawdy-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: development
    environment:
      APP_ENV: dev
    volumes:
    - .:/var/www/html
    healthcheck:
      test: ["CMD-SHELL", "php-fpm -t"]
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:12.3
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/mariadb/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10
  node:
    image: shawdy-node
    build:
        context: .
        dockerfile: docker/node/Dockerfile
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "127.0.0.1:5173:5173"
    command: npm run dev -- --host 0.0.0.0

  playwright:
    image: mcr.microsoft.com/playwright:v1.62.1-noble
    working_dir: /app
    volumes:
      - ./frontend:/app
    depends_on:
      nginx:
        condition: service_started

volumes:
  mariadb_data:
