framework:
  rate_limiter:
    short_url_creation:
      policy: token_bucket
      limit: 10
      rate:
        interval: '5 seconds'
        amount: 1

    abuse_report_submission:
      policy: token_bucket
      limit: 3
      rate:
        interval: '10 minutes'
        amount: 1
