#!/bin/bash

TEST_DATABASE="${DATABASE_NAME}_test"

mariadb -u root -p"${MYSQL_ROOT_PASSWORD}" <<-EOSQL
    CREATE DATABASE IF NOT EXISTS \`${TEST_DATABASE}\`;

    GRANT ALL PRIVILEGES ON \`${TEST_DATABASE}\`.* TO '${MYSQL_USER}'@'%';
EOSQL
