name: Docker

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  hadolint:
    name: Lint Dockerfiles
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Lint Dockerfiles
        uses: hadolint/hadolint-action@v3.4.0
        with:
          recursive: true
          dockerfile: docker/Dockerfile
