name: Documentation

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  markdownlint:
    name: Lint Markdown
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@v24
        with:
          globs: '**/*.md'

  links:
    name: Check links
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Check Markdown links
        uses: lycheeverse/lychee-action@v2
        with:
          args: './**/*.md'
          fail: true
          failIfEmpty: false