name: PHP

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    name: PHPUnit
    runs-on: ubuntu-latest

    env:
      APP_ENV: test
      DATABASE_HOST: 127.0.0.1

    services:
      mariadb:
        image: mariadb:12.3
        env:
          MARIADB_ROOT_PASSWORD: test_only_do_not_use_in_production
          MARIADB_DATABASE: shawdy_app_test
          MARIADB_USER: app
          MARIADB_PASSWORD: test_only_do_not_use_in_production
        ports:
          - 3306:3306
        options: >-
          --health-cmd="healthcheck.sh --connect --innodb_initialized"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: mbstring, intl, pdo_mysql, zip
          tools: composer

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Prepare Database Schema
        run: |
          php bin/console doctrine:database:create --if-not-exists
          php bin/console doctrine:schema:update --force

      - name: Execute Tests via PHPUnit
        run: vendor/bin/phpunit
