name: PHP

on:
  pull_request:
    paths:
      - '**.php'
      - 'composer.json'
      - 'composer.lock'
      - 'phpstan.dist.neon'
      - '.php-cs-fixer.dist.php'
      - 'phpunit.dist.xml'
      - '.github/workflows/php.yml'
  push:
    branches:
      - main
    paths:
      - '**.php'
      - 'composer.json'
      - 'composer.lock'
      - 'phpstan.dist.neon'
      - '.php-cs-fixer.dist.php'
      - 'phpunit.dist.xml'
      - '.github/workflows/php.yml'

jobs:
  tests:
    name: PHP Checks
    runs-on: ubuntu-latest

    env:
      APP_ENV: test
      DATABASE_HOST: 127.0.0.1

    services:
      mariadb:
        image: mariadb:12.3
        env:
          MARIADB_ROOT_PASSWORD: dev_only_do_not_use_in_production
          MARIADB_DATABASE: shawdy_app_test
          MARIADB_USER: app
          MARIADB_PASSWORD: dev_only_do_not_use_in_production
        ports:
          - 3306:3306
        options: >-
          --health-cmd="healthcheck.sh --connect --innodb_initialized"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: mbstring, intl, pdo_mysql, zip
          tools: composer

      - name: Cache Composer packages
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Scan dependencies for security vulnerabilities
        run: composer audit

      # --- CODE STYLE & STATIC ANALYSIS (Using Dev Container) ---
      - name: Coding standards analysis via PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix --dry-run --diff

      - name: Build Symfony container for PHPStan
        env:
            APP_ENV: dev
        run: php bin/console cache:warmup

      - name: Lint Symfony container
        env:
          APP_ENV: dev
        run: php bin/console lint:container

      - name: Static Analysis via PHPStan
        run: vendor/bin/phpstan analyse

      # --- DATABASE DEPENDENT CHECKS (Using Test Container) ---
      - name: Create test database
        run: php bin/console doctrine:database:create --if-not-exists

      - name: Validate Doctrine schema mapping
        run: php bin/console doctrine:schema:validate --skip-sync

      - name: Prepare Database Schema
        run: php bin/console doctrine:schema:update --force

      - name: Execute Tests via PHPUnit
        run: vendor/bin/phpunit
